openapi: 3.0.0
info:
  title: Pet Store API
  version: 1.0.0
  description: A simple pet store API for demonstration

servers:
  - url: https://api.petstore.com/v1
    description: Production server

tags:
  - name: pets
    description: Pet management

paths:
  /pets:
    get:
      summary: List all pets
      description: Returns a list of all pets in the store
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: Maximum number of pets to return
          required: false
          schema:
            type: integer
            format: int32
            default: 20
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '500':
          description: Internal server error

    post:
      summary: Create a pet
      description: Add a new pet to the store
      operationId: createPet
      tags:
        - pets
      requestBody:
        description: Pet to add
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
      responses:
        '201':
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid input

  /pets/{petId}:
    get:
      summary: Get a pet by ID
      description: Returns a single pet
      operationId: getPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Pet details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          description: Unique identifier
        name:
          type: string
          description: Pet name
        tag:
          type: string
          description: Pet category tag

    NewPet:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Pet name
        tag:
          type: string
          description: Pet category tag
